package com.epam.liavitskaya.main.enumeration;

public enum CommandName {

	SIGN_IN, SIGN_OUT, REGISTRATION, CHANGE_STATUS, CHANGE_ROLE, MAKE_ADMIN_USER, ADD_BOOK, ORDER_BOOK, CANCEL_ORDER, REVIEW_PROFILE, REVIEW_PROFILE_ID, EDIT_PROFILE, EDIT_BOOK, EDIT_BOOK_DESCRIPTION, WRITE_OFF_BOOK, SHOW_ALL_BOOKS, SHOW_ALL_AVAILABLE_BOOKS, SHOW_ALL_USERS, WRONG_REQUEST

}
